version: '3'

services:
  master:
    image: locustio/locust
    ports:
      - "8089:8089" # Web UI
      - "5557:5557" # Communication with workers
      - "5558:5558"
    volumes:
      - ./:/mnt/locust # Mount current directory to access locustfile.py
    command: -f /mnt/locust/locustfile.py --master -H http://host.docker.internal:8080
    # The -H flag sets the target host for the tests.
    # host.docker.internal is a special DNS name that resolves to the host machine's IP from within a Docker container.

  worker:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master
    # This command tells the container to act as a worker and connect to the 'master' service.
